### ISSUE TITLE
Install JDK 8

### ISSUE THREAD

**Issue by glarimy** [glarimy/glarimy-quiz-app#1]

**Comment by venumittapalli576** [comment]
installed jdk8 to contribute to the project

**Comment by glarimy** [comment]
Issues with multiple assignees are not to be closed by individuals. Just add the comment with status. I will close it once all the assignees update their status

**Comment by venumittapalli576** [comment]
k sure sir

**Comment by ramakrishna5a1** [comment]
Downloaded the jdk8 and installed in my machine from the provided link.

**Comment by glarimy** [comment]
Pratyusha is yet to update the status on this issue.

**Comment by Pratyusha-Bodapati** [comment]
installed
