### ISSUE TITLE
Review the solution architecture model

### ISSUE THREAD

**Issue by glarimy** [glarimy/glarimy-quiz-app#12]
![class-model](https://user-images.githubusercontent.com/8440589/39715940-75c7808c-524c-11e8-9318-3d1f3eb3da8a.jpg)
![collaborations](https://user-images.githubusercontent.com/8440589/39715946-7e9f4eb0-524c-11e8-9495-a846710a2ffa.jpg)

**Comment by venumittapalli576** [comment]
sir  i have a query you mentioned that QuestionService as interface why not got with class. I mean that as it is interface, implementation of methods need to be done in another activity. Implementation need to be done in main activity.

**Comment by glarimy** [comment]
Its always a best practice to separate interface from its implementation so that you achieve loose coupling. Its like your datacard and laptop are connected though USB interface so the datacard and laptop are free to be connected with any other USB counterparts. 

There is a flaw in the design diagram. As I mentioned in the meeting, even ScoringService is also an interface.

**Comment by venumittapalli576** [comment]
I sir can I write the implementation of interfaces in main activity are go
with new class

**Comment by glarimy** [comment]
Every interface and class will be in their own .java files. And write your comments in appropriate issue only. This issue #12 is only about design review. If you have questions on other issues, please comment it on that specific issue. I will be able to answer you appropriately.

**Comment by glarimy** [comment]
![glarimy-quiz app-classes](https://user-images.githubusercontent.com/8440589/39957054-d4d66e06-5609-11e8-987f-186eab4c2727.jpg)
 Review the updated class diagram. Notice the changes.

**Comment by glarimy** [comment]
![glarimy-quiz-app-sequences](https://user-images.githubusercontent.com/8440589/39957064-0d96a6b6-560a-11e8-9857-bba0173b031f.jpg)

Review the updated sequence diagram. Notice the changes.

**Comment by glarimy** [comment]
![glarimy-quiz-app-activity](https://user-images.githubusercontent.com/8440589/39957073-24f8cf6e-560a-11e8-9d9e-5053701d1d45.jpg)
Review the flow diagram of the app. Refer to the UI mock flow updated in #17

**Comment by glarimy** [comment]
Closing since there are no comments.
