### ISSUE TITLE
Create Models

### ISSUE THREAD

**Issue by glarimy** [glarimy/glarimy-quiz-app#13]
Code for com.glarimy.quiz.model package with Question, Answer and Score classes as Java Beans.
Refer to the class models described in  #12.
Once completed, check in the code with appropriate comments.

**Comment by ramakrishna5a1** [comment]
sir implemented the Code for com.glarimy.quiz.model package (#12) with Question, Answer and Score classes as Java Beans with get and set methods with proper comments for each class

now can i commit the code and push into github...?

**Comment by glarimy** [comment]
Good work. I found one issue with the model that I have shared. The answer class is modeled as if the properties are public. I am sorry for that. Please code all the three model classes to have protected fields and check-in the code.

**Comment by ramakrishna5a1** [comment]
Ok sir

**Comment by ramakrishna5a1** [comment]
sir Answer class properties are also changed from public to protected.now all three classes(Answer,Question,Scores) properties are protected.

**Comment by glarimy** [comment]
Please check-in the code.

**Comment by glarimy** [comment]
Since @ramakrishna5a1 has checked-in the code, I am closing this issue. It would have been good if @ramakrishna5a1 has closed the issue already!
