### ISSUE TITLE
Create service interfaces and stub implementation

### ISSUE THREAD

**Issue by glarimy** [glarimy/glarimy-quiz-app#14]
Start activity on this issue only after #13 is closed. 
Code for com.glarimy.quiz.service package with QuestionService and ScoringService.
Add complete JavaDoc for both the interface classes.
Create stub implementation for GlarimyQuestionService and SimpleScoringService.
Refer to the class models described in #12.
Once completed, check in the code with appropriate comments.

**Comment by glarimy** [comment]
@venumittapalli576, the issue #13 is now closed. Please start activity on this issue #14. Create the package com.glarimy.quiz.service. Create interfaces as specified in the design (refer #12), write the javadoc, check-in the code and update the status here. Once the interfaces are reviewed, then you can proceed to start writing the stub implementation.

**Comment by venumittapalli576** [comment]
k sure sir i am working on it

**Comment by venumittapalli576** [comment]
created service interfaces along with javadoc .If you review the interfaces i will work on stub implementation

**Comment by glarimy** [comment]
Thanks for checkin. However, it is not confirming with the design. Please fix the following:

1. The file QuestionService.java must contain only the interface named QuestionService. Remove everything else from the file.
2. The file ScoringService.java must contain only the interface named ScoringService. Remove everything else from the file.
3. The get() method of QuestionService must return Question (not int). Refer the design diagram. Import the class Question from package com.glarimy.quiz.model.
4. The getAnswer() method of QuestionService must return Answer (not int). Refer the design diagram. Import the class Answer from the package com.glarimy.quiz.model.
5. The evaluate() method of ScoringService must return Score (not int). Refer the design diagram. Import the class Score from package com.glarimy.quiz.model.
6. The implementation of QuestionService must be GlarimyQuestionService (not QuestionServic). And this implementation must be in a separate file named GlarimyQuestionService.java in the package com.glarimy.quiz.service. Refer the design.
7. The implementation of ScoringService must be SimpleScoringService (not ScoringServic). And this implementation must be in a separate file named SimpleScoringService.java in the package com.glarimy.quiz.service. Refer the design.
8. We do not need any code implementation in the GlarimyQuestionService and SimpleScoringService, except stub code. 
9. The JavaDoc is not upto the mark. JavaDoc is required only for the QuestionService and ScoringService interfaces. Not for the implementations. 

Fix all these issues by CoB today and check-in the code.

**Comment by venumittapalli576** [comment]
K sure sir  but I am not  getting clear cut idea regarding stub  implementation  can u guide me. I contacted our sir He said to contact you

**Comment by glarimy** [comment]
Don't worry. Look at this sample:

Sample Interface:  DictionaryService
Sample Code with JavaDoc: DictionaryService.java

/**
 * This service provides meaning to English words. 
 * Author: Krishna
 * Since: 2018
 */
class DirectionaryService {
  /** 
   * Returns one meaning for the supplied word.
   * Parameters: 
   * word: The English word for which the meaning is required.
   * Return: Meaning of the word in English
   * Throws: WordNotFoundException - if there is no meaning found for the supplied word.
   */
   public String findMeaning(String word) throws WordNotFoundException;

  /**
   * It returns the number of words that are part of the dictionary.
   * Parameters: None
   * Returns the number of words in the dictionary
  */
   public int numberOfWords();
}

Sample Stub Code: SimpleDictionaryService.java

class SimpleDictionaryService implements DictionaryService {
   public String find(String word) throws WordNotFoundException {
         // This is just stub implementation to compile the code.
         // TBD: Actual implementation
         return null;
   }
   public int numberOfWords() {
         // This is just stubcode for successful compilation.
         // TBD: Actual implementation
         return 0;
} 

Hope this helps.

**Comment by venumittapalli576** [comment]
yes sir it helped me a lot thank you sir

**Comment by venumittapalli576** [comment]
sir i have checked in the code

**Comment by glarimy** [comment]
Thanks. Great job!

**Comment by glarimy** [comment]
Please address comments on the code made by @ramakrishna5a1. Refer the #20 for comments. Check-in the code after the comments are addressed.

**Comment by venumittapalli576** [comment]
Changed and updated the docfile

**Comment by glarimy** [comment]
Thank you!

**Comment by glarimy** [comment]
Make changes to the ScoringService as per the new design in #12.

**Comment by venumittapalli576** [comment]
Sir I had made changes and committed the new javadocs and 
stubimplementation

**Comment by glarimy** [comment]
Thanks you!
