### ISSUE TITLE
Add email notifications for build jobs

### ISSUE THREAD

**Issue by glarimy** [glarimy/glarimy-quiz-app#15]
Configure the Jenkins job in such a way that all the participants on this project @ramakrishna5a1, @Pratyusha-Bodapati, @venumittapalli576 and krishna@glarimy.com receives the results of every build job.

**Comment by glarimy** [comment]
Any update?

**Comment by glarimy** [comment]
Complete this task by CoB today. The build automation must be completed by tomorrow.

**Comment by Pratyusha-Bodapati** [comment]
sir due to some internet problem installation problem is occurring....i will complete the work by 2 or 3 hrs delay...

**Comment by glarimy** [comment]
One way other way, the task must be completed today and I should receive automated build mail to krishna@glarimy.com from Jenkins.

**Comment by Pratyusha-Bodapati** [comment]
Ok sure sir...currently iam working on it

**Comment by Pratyusha-Bodapati** [comment]
successfully added email notifications for build jobs

**Comment by glarimy** [comment]
Appreciated. Closing the issue.
