### ISSUE TITLE
Automate the build job

### ISSUE THREAD

**Issue by glarimy** [glarimy/glarimy-quiz-app#16]
Automate the build job in such a way that every time new code is pushed into GIT, the build job kicked-off automatically. Give 1 hour as the poll interval.

**Comment by glarimy** [comment]
Any update?

**Comment by glarimy** [comment]
Complete this task my CoB tomorrow. The build automation must be completed by tomorrow.

**Comment by Pratyusha-Bodapati** [comment]
automated the build jobs for every one hour

**Comment by glarimy** [comment]
Good work. Closing the issue.
