### ISSUE TITLE
Create mockup ppt for UI

### ISSUE THREAD

**Issue by glarimy** [glarimy/glarimy-quiz-app#17]
Create mockup screen for the UI flows:
Flow 1: What is seen when the app opens
Flow 2: What is seen when the app opens but there is no internet connectivity
Flow 3: What is seen when a question is displayed
Flow 4: What is seen when a question is answered

The UI mockup should be complete in terms of fonts, colors, dimensions, text, UI controls.
Attach the PPT to the issue, once done.
This is not a team activity. Each assignee should come up with their own ideas, individually.
All the three mockups will be reviewed before finalizing the UI.

**Comment by glarimy** [comment]
[gqa-mocks.pptx](https://github.com/glarimy/glarimy-quiz-app/files/1990372/gqa-mocks.pptx)

A sample for creating the mock-up screens.

**Comment by glarimy** [comment]
Please complete this activity by CoB today.

**Comment by ramakrishna5a1** [comment]
[glarimy-quiz-mockup ppt for ui.pptx](https://github.com/glarimy/glarimy-quiz-app/files/1995298/glarimy-quiz-mockup.ppt.for.ui.pptx)

**Comment by venumittapalli576** [comment]
[glarimy-quiz ppt for ui.pptx](https://github.com/glarimy/glarimy-quiz-app/files/1996642/glarimy-quiz.ppt.for.ui.pptx)

**Comment by glarimy** [comment]
Thank you all. We will review it in today's scrum meeting.

**Comment by glarimy** [comment]
Finalized UI mock flows: 
[glarimy-quiz-app-ui.pdf](https://github.com/glarimy/glarimy-quiz-app/files/1997573/glarimy-quiz-app-ui.pdf)

**Comment by glarimy** [comment]
Closing as I haven't received any comments.
