### ISSUE TITLE
Review com.glarimy.quiz.model

### ISSUE THREAD

**Issue by glarimy** [glarimy/glarimy-quiz-app#18]
Review the code for adherence to the proposed design and Java coding practices.

**Comment by glarimy** [comment]
Complete this task and add your review comments here by CoB today.

**Comment by venumittapalli576** [comment]
can say this issue clearly i can not under it

**Comment by glarimy** [comment]
Review the code under the package com.glarimy.quiz.model that was checked-in by @ramakrishna5a1 as part of issue #13. Read the history of the issue #13 and see if the code is matching the design changes. If you find any mismatches, record them here as a comment so that I will reopen #13. If you find no mismatches, put comment saying that you are find with it.

**Comment by venumittapalli576** [comment]
Sir I have gone through the code as per my view It is according to the design

**Comment by glarimy** [comment]
Thanks for the effort. Closing it.
