### ISSUE TITLE
Review com.glarimy.quiz.service.ScoringService

### ISSUE THREAD

**Issue by glarimy** [glarimy/glarimy-quiz-app#19]
Review the interface design for its adherence to the design and Java coding practices. Also review the JavaDoc associated with it.

**Comment by glarimy** [comment]
Complete this activity by CoB today.

**Comment by ramakrishna5a1** [comment]
sir in ScoringService interface  java code is reviewed and also done some changes in java doc,can i the commit code now.

**Comment by ramakrishna5a1** [comment]
The interface design for its adherence to the design and Java coding practices.

and the javaDoc is also good and clear.

**Comment by glarimy** [comment]
Done!
