### ISSUE TITLE
Review com.glarimy.quiz.service.QuestionService

### ISSUE THREAD

**Issue by glarimy** [glarimy/glarimy-quiz-app#20]
Review the interface for its adherence to the design and Java coding practices. Also review the JavaDoc.

**Comment by glarimy** [comment]
Complete this activity by CoB today.

**Comment by ramakrishna5a1** [comment]
sir in QuestionService interface java code is reviewed and also done some changes in javaDoc,can i the commit code now.

**Comment by glarimy** [comment]
No. Please do not check-in the code. Make your suggestions as comments here in the issue. Original author of the code may accept or reject your comments. If the author accepts your comments, he or she incorporates the changes. So, please record your comments here by specifying what can be improved, why it must be improved.

**Comment by ramakrishna5a1** [comment]
ok sir

**Comment by ramakrishna5a1** [comment]
The code in the interface is adherence to the design and Java coding practices

in javaDoc
1,The description of the each method has to be some what clear.like what is the use of the method and what it will be returns.
2,The parameter description to be some what clear.

**Comment by glarimy** [comment]
Thanks.
