### ISSUE TITLE
Implement com.glarimy.quiz.SimpleScoringService

### ISSUE THREAD

**Issue by glarimy** [glarimy/glarimy-quiz-app#22]
Implement the SimpleScoringService and make sure that all the test cases are passing.

**Comment by glarimy** [comment]
Complete this task by CoB tomorrow!

**Comment by venumittapalli576** [comment]
Implemented simplescoringservice and checked in the code

**Comment by glarimy** [comment]
Review comment 1: The method evaluate() is only checking the correctness of the ticked option. It must also update the current score.

Review comment 2: The method getCurrentScore() is supposed to just return the current score.

Refactor the code based on the above comments and check it in.

**Comment by venumittapalli576** [comment]
Refactored the code of simplescoringservice

**Comment by glarimy** [comment]
Good job.

**Comment by glarimy** [comment]
Found a problem with your code. The currentScore property is being used at lines 22, 23, 27 and 28 without initialization. It leads to nullpointerexception. Please initialize the currentScore to new Score() in the contructor of SimpleScoringService.

**Comment by venumittapalli576** [comment]
k sir i am working on it

**Comment by venumittapalli576** [comment]
completed and checked in the code

**Comment by glarimy** [comment]
Thanks!
