### ISSUE TITLE
Create glarimy theme

### ISSUE THREAD

**Issue by glarimy** [glarimy/glarimy-quiz-app#25]
Externalize all the colors into res/values/colors.xml. Create glarimy theme in res/values/styles.xml by using the externalized colors.

**Comment by glarimy** [comment]
The UI part of the application uses several colors on the screen. Look at the latest mockup flow PDF that was shared. Some of the colors from the mockup include black, white, straw-berry, aqua and etc., 

Separating the colors from the Java code is always good. It enables changing the colors during the lifetime, without changing the Java code.

Here the task:

1. Check-out the file https://github.com/glarimy/glarimy-quiz-app/blob/master/app/src/main/res/values/colors.xml on to your local machine. (You do not required Andorid Studio. Just check-out the file using any command line tool, open the file in notepad/textpad/etc.,

2. Identify all colors texts from the UI mockup screens and register them in the checked-out colors.xml. Use any tool to find the hex-codes for the colors that the mockup is using. 

3. Once completed, check-in the file and update the issue.

Complete the task by CoB today.

**Comment by glarimy** [comment]
Any update?

**Comment by Pratyusha-Bodapati** [comment]
Working sir...i will complete it by today

**Comment by Pratyusha-Bodapati** [comment]
sir added strings and check-in the code.

**Comment by Pratyusha-Bodapati** [comment]
sir added colors and check-in the code.

**Comment by glarimy** [comment]
Thanks! Appreciated!
