### ISSUE TITLE
Connection Error Flow UI

### ISSUE THREAD

**Issue by glarimy** [glarimy/glarimy-quiz-app#28]
Develop the UI flow that displays the connection failure.

**Comment by glarimy** [comment]
Implement the flow covered in the screen 23/23 of the finalized UI flow referred. It includes coding the MainActivity, layouts and etc., No images to be used.

Complete this activity by CoB tomorrow.

**Comment by venumittapalli576** [comment]
sir if i create activity showerrormessage the xml file is creating as activity_showerrormessage can we create like this are change the name of xml file also to showerrormessage

**Comment by glarimy** [comment]
No issues!

**Comment by venumittapalli576** [comment]
Sir Implemented and checked in the code

**Comment by glarimy** [comment]
Thanks!
