### ISSUE TITLE
New Question UI Flow

### ISSUE THREAD

**Issue by glarimy** [glarimy/glarimy-quiz-app#29]
Develop the UI flow that displays a question on the screen.

**Comment by glarimy** [comment]
Implement from 4/23 slide to 9/23 slide, by CoB today.

**Comment by ramakrishna5a1** [comment]
sir from layouts 4 to 23 i observed there are saperate layouts for individual views like title view,optoin view 1,option view 2.....

1,now my question is all  the views  to be displayed in a same layout with some delay or the individual layouts to be displayed with some delay.?

**Comment by ramakrishna5a1** [comment]
sir from layouts 4 to 9 i observed there are saperate layouts for individual views like title view,optoin view 1,option view 2.....

1,now my question is all the views to be displayed in a same layout with some delay or the individual layouts to be displayed with some delay.?

**Comment by glarimy** [comment]
You take your own decision based on pros and cons. I personally prefer one single layout with code manipulation from the corresponding activity. But, I leave the decision to you. Finally, it should work the way it is expected.

**Comment by ramakrishna5a1** [comment]
sir implemented all the layouts(2 to 9) in a single layout and the data is static for now after it will be  changed when programming the corresponding activity. 

and i am checked in the code.

**Comment by glarimy** [comment]
You can checkin the code. However, this task include only just only layouts! The task includes fetching the question from the QuestionService and displaying as per the slides 4-9. Let me know once you complete that part of the code as well so that we will close it.

**Comment by ramakrishna5a1** [comment]
completed sir and i have checked in the code.

**Comment by glarimy** [comment]
Thanks! I believe the code you checked-in is with static questions & options. Continue with the rest of the work of fetching the question and replacing the static text with the real question and options. Update the status once the that code is also check in.

**Comment by ramakrishna5a1** [comment]
sir i am currently working on GlarimyQuestionService to get the data from cloud i am update the status soon.

**Comment by glarimy** [comment]
Any update on this issue? I am not seeing updates from you on the issues assigned to you. Please make sure you stick to the process.

**Comment by ramakrishna5a1** [comment]
sir for the last two days i am completely worked on the GlarimyQuestionService due to the involvement of threading concept and Json concept that will take much time sir 

sir new question UI flow is almost complete i am checkin the code with in the 2 hours sir.

sir i will not repeat this type of situation again.
