### ISSUE TITLE
Build Failed: Urgent

### ISSUE THREAD

**Issue by glarimy** [glarimy/glarimy-quiz-app#43]
Urgent. Pls fix the build error. PFB for the build trace:
[build-37.txt](https://github.com/glarimy/glarimy-quiz-app/files/2025000/build-37.txt)

**Comment by ramakrishna5a1** [comment]
ok sir

**Comment by venumittapalli576** [comment]
ok sir

**Comment by Pratyusha-Bodapati** [comment]
Ok sir

**Comment by ramakrishna5a1** [comment]
Sir the error is occured because styles.xml file is committed with a colour resource reference which is not exist in the color.xml file 

Fixed that problem and build is running normally

**Comment by venumittapalli576** [comment]
resource file is has been corrupted so build failed no it is working fine sir

**Comment by Pratyusha-Bodapati** [comment]
sir build is running fine

**Comment by glarimy** [comment]
Thanks! We should avoid the future build fails. Please take care!
