### ISSUE TITLE
Run the app on Android device using USB connector

### ISSUE THREAD

**Issue by glarimy** [glarimy/glarimy-quiz-app#6]

**Comment by venumittapalli576** [comment]
created splash and tested in android successfully in android device

**Comment by ramakrishna5a1** [comment]
designed splash screen UI, designed layout background design and executed the app on android app successfully

**Comment by glarimy** [comment]
do not make any changes to the code unless asked for. please remove the changes, make sure that it is still running successfully and update the status.

**Comment by ramakrishna5a1** [comment]
app is still running successfully. i am just designed layout.

**Comment by ramakrishna5a1** [comment]
app is still running successfully. i just designed layout.

**Comment by glarimy** [comment]
the layout is yet to be finalized. do not put any effort unless it is assigned to you. revoke all the changes to the actual code and confirm the status. this issue will not be closed unless both the assignees update the status, after removing the code changes.
